on:
  pull_request:
    paths:
      - 'Application_virtual_machine/**'
  workflow_dispatch:

name: Run Linux Virtual Machine

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Create Resource Group (if not exists)
      run: |
        az group create --name Student --location eastus || echo "Resource Group already exists"

    - name: Deploy Virtual Machine
      run: | 
        az deployment group create --resource-group Student --template-file create_linux_vm_template.json --parameters create_linux_vm_parameters.json
