on: [push]

name: Run Azure Login With a Service Principal Secret

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Create Resource Group (if not exists)
      run: |
        az group create --name Student --location eastus || echo "Resource Group already exists"

    - name: Deploy Virtual Network
      run: |
        az deployment group create --resource-group Student --template-file Virtual_Network_Azure/create_virtual_network.json

    - name: Deploy Load Balancer
      run: |
        az deployment group create --resource-group Student --template-file Load_Balancer/create_load_balancer.json
